#-------------------------------------------------
#  FILE:   Makefile
#  AUTHOR: Simon Sedlacek, FIT
#  EMAIL:  xsedla1h@stud.fit.vutbr.cz
#  DATE:   19.4.2019
#  BRIEF:  Makefile with all the necessary targets for manipulating the project
#  NOTE:   IVS-2019-project2, Vychodni Nemci a Severni Madari
#-------------------------------------------------


.PHONY: all clean test doc run profile

all: 

clean:

test:

doc:

run:

profile:
